from pathlib import Path
lines = [
'import json',
'from pathlib import Path',
'',
'BASE = Path(r"D:\ECOM_LISTING_AGENT_MVP")',
'',
'def read_json(rel_path):',
'    p = BASE / Path(rel_path)',
'    if not p.exists():',
'        return {}, str(p), False',
'    return json.loads(p.read_text(encoding="utf-8")), str(p), True',
'',
'def main():',
'    decision_data, decision_path, decision_exists = read_json(r"storage\state_compact_core\compact_core_stage9_decision_gate_v1.json")',
'    summary_data, summary_path, summary_exists = read_json(r"storage\state_compact_core\compact_core_stage9_summary_v1.json")',
'    archive_dir = BASE / Path(r"storage\memory\archive")',
'    archive_dir.mkdir(parents=True, exist_ok=True)',
'    payload = {}',
'    payload["date"] = "2026-04-19"',
'    payload["project"] = "ECOM_LISTING_AGENT_MVP_CONTROL_ROOM"',
'    payload["archive_type"] = "TRANSITION_POST_STAGE9_MEMORY_REFRESH_V1"',
'    payload["status"] = "OK"',
'    payload["stage"] = 9',
'    payload["stage9_confirmed"] = bool(decision_data.get("stage9_ready")) and bool(decision_data.get("decision_ready")) and decision_data.get("decision") == "STAGE_9_CONFIRMED"',
'    payload["decision"] = decision_data.get("decision", "")',
'    payload["confirmed_layers_count"] = decision_data.get("confirmed_layers_count", 0)',
'    payload["summary_exists"] = summary_exists',
'    payload["decision_exists"] = decision_exists',
'    payload["confirmed_layers"] = summary_data.get("confirmed_layers", [])',
'    payload["main_result"] = "STAGE_9_CONFIRMED_AND_READY_FOR_POST_STAGE9_DIRECTION_PLAN"',
'    payload["errors_this_chat"] = [',
'        "utf8_bom_or_feff_in_python_files",',
'        "broken___main___guard_in_preview_contract",',
'        "fragile_direct_echo_build_caused_missing_lines_and_missing_keys",',
'        "cmd_traps_with_special_characters_and_partial_writes",',
'        "windows_path_escape_errors_in_archive_script",',
'        "late_chat_degradation_after_many_steps"',
'    ]',
'    payload["solutions_this_chat"] = [',
'        "first_real_audit_then_fix",',
'        "sanitize_bom_before_logic_repair",',
'        "if_file_breaks_twice_rebuild_full_file",',
'        "prefer_writer_script_over_fragile_direct_echo_build",',
'        "use_raw_windows_paths_in_generated_python_files",',
'        "after_ok_audit_only_one_next_step",',
'        "archive_first_then_prompt_for_new_chat"',
'    ]',
'    payload["mandatory_rules_next_chat"] = [',
'        "start_with_canonical_9_step_audit",',
'        "project_specific_only",',
'        "one_step_only",',
'        "real_verification_before_action",',
'        "include_previous_errors_and_fixes_in_transition_prompt",',
'        "prefer_writer_script_when_direct_echo_build_becomes_fragile",',
'        "build_post_stage9_direction_plan_before_new_technical_layers"',
'    ]',
'    payload["memory_note"] = "UI memory may be empty or delayed; archive and transition prompt remain source of truth for next chat."',
'    payload["next_step"] = "open_new_chat_and_build_post_stage9_direction_plan_v1"',
'    archive_file = archive_dir / "transition_post_stage9_memory_refresh_v1.json"',
'    archive_file.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")',
'    prompt_lines = []',
'    prompt_lines.append("?? CONTINUATION - ECOM OS CONTROL ROOM (POST STAGE 9 MEMORY REFRESH)")',
'    prompt_lines.append("")',
'    prompt_lines.append("ПРОЕКТ:")',
'    prompt_lines.append("ECOM_LISTING_AGENT_MVP")',
'    prompt_lines.append("")',
'    prompt_lines.append("Я продолжаю новый чат после архивации.")',
'    prompt_lines.append("")',
'    prompt_lines.append("ПОДТВЕРЖДЁННЫЙ СТАТУС:")',
'    prompt_lines.append("- Stage 9 confirmed")',
'    prompt_lines.append("- decision = STAGE_9_CONFIRMED")',
'    prompt_lines.append("- confirmed_layers_count = 10")',
'    prompt_lines.append("- stage9_ready = True")',
'    prompt_lines.append("")',
'    prompt_lines.append("ОШИБКИ ПРОШЛОГО ЧАТА:")',
'    for item in payload["errors_this_chat"]:',
'        prompt_lines.append("- " + item)',
'    prompt_lines.append("")',
'    prompt_lines.append("КАК ИХ ИСПРАВЛЯЛИ / LESSONS LEARNED:")',
'    for item in payload["solutions_this_chat"]:',
'        prompt_lines.append("- " + item)',
'    prompt_lines.append("")',
'    prompt_lines.append("ОБЯЗАТЕЛЬНЫЙ СТАРТ НОВОГО ЧАТА:")',
'    prompt_lines.append("- сначала каноничный audit по 9-step линии")',
'    prompt_lines.append("- потом определить current stage, direction, next step")',
'    prompt_lines.append("- если есть риск повторения ошибки: STOP и проверка архивов/аудитов/ошибок")',
'    prompt_lines.append("")',
'    prompt_lines.append("КАНОНИЧНЫЙ ФОРМАТ ОТВЕТА:")',
'    prompt_lines.append("1) Краткий анализ")',
'    prompt_lines.append("2) Что делаем")',
'    prompt_lines.append("3) Один CMD блок")',
'    prompt_lines.append("4) Проверка")',
'    prompt_lines.append("5) Audit")',
'    prompt_lines.append("6) Что ожидаем")',
'    prompt_lines.append("")',
'    prompt_lines.append("ТЕКУЩАЯ ЦЕЛЬ:")',
'    prompt_lines.append("?? build_post_stage9_direction_plan_v1")',
'    prompt_lines.append("?? не прыгать сразу в новые технические слои")',
'    prompt_lines.append("?? сначала сделать post-stage9 audit, direction plan и следующий структурированный план")',
'    prompt_file = archive_dir / "transition_post_stage9_memory_refresh_prompt_v1.txt"',
'    prompt_file.write_text("\n".join(prompt_lines) + "\n", encoding="utf-8")',
'    print("TRANSITION_POST_STAGE9_MEMORY_REFRESH_AUDIT")',
'    print("status = OK")',
'    print("stage9_confirmed =", payload["stage9_confirmed"])',
'    print("decision =", payload["decision"])',
'    print("confirmed_layers_count =", payload["confirmed_layers_count"])',
'    print("archive_file =", str(archive_file))',
'    print("prompt_file =", str(prompt_file))',
'',
'if __name__ == "__main__":',
'    main()',
]
Path(r'D:\ECOM_LISTING_AGENT_MVP\write_transition_post_stage9_memory_refresh_v1.py').write_text('\n'.join(lines) + '\n', encoding='utf-8')
