from pathlib import Path
lines = [
'import json',
'from pathlib import Path',
'',
'BASE = Path(r"D:\ECOM_LISTING_AGENT_MVP")',
'',
'def main():',
'    source = BASE / Path("storage\\state_compact_core\\compact_core_runner_payload_v1.json")',
'    payload = {}',
'    payload["layer"] = "COMPACT_CORE_RUNNER_HANDOFF_GATE_V1"',
'    payload["mode"] = "PROJECT_SPECIFIC_ONLY"',
'    payload["stage"] = 9',
'',
'    if not source.exists():',
'        payload["status"] = "BROKEN"',
'        payload["source_exists"] = False',
'        payload["runner_payload_ready"] = False',
'        payload["handoff_ready"] = False',
'        payload["reason"] = "runner_payload_missing"',
'        payload["next_step"] = "restore_runner_payload_v1"',
'',
'    else:',
'        data = json.loads(source.read_text(encoding="utf-8"))',
'        runner_payload_ready = bool(data.get("runner_payload_ready"))',
'        runner_payload = data.get("runner_payload", {})',
'        title = runner_payload.get("title", "")',
'        price = runner_payload.get("price", "")',
'        description = runner_payload.get("description", "")',
'        html = runner_payload.get("html", "")',
'        images = runner_payload.get("images", [])',
'        handoff_ready = runner_payload_ready and bool(title) and bool(str(price)) and bool(description) and bool(html) and bool(images)',
'        if handoff_ready:',
'            payload["status"] = "OK"',
'            payload["next_step"] = "runner_handoff_ready_for_next_compact_core_layer"',
'        else:',
'            payload["status"] = "BLOCKED"',
'            payload["next_step"] = "runner_handoff_not_ready_stop_here"',
'        payload["source_exists"] = True',
'        payload["source_file"] = str(source)',
'        payload["runner_payload_ready"] = runner_payload_ready',
'        payload["handoff_ready"] = handoff_ready',
'        payload["gate_checks"] = {}',
'        payload["gate_checks"]["title_ready"] = bool(title)',
'        payload["gate_checks"]["price_ready"] = bool(str(price))',
'        payload["gate_checks"]["description_ready"] = bool(description)',
'        payload["gate_checks"]["html_ready"] = bool(html)',
'        payload["gate_checks"]["images_ready"] = bool(images)',
'        payload["summary"] = {}',
'        payload["summary"]["images_count"] = len(images)',
'        payload["summary"]["title_length"] = len(title)',
'',
'    out_file = BASE / Path("storage\\state_compact_core\\compact_core_runner_handoff_gate_v1.json")',
'    out_file.parent.mkdir(parents=True, exist_ok=True)',
'    out_file.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")',
'',
'    print("COMPACT_CORE_RUNNER_HANDOFF_GATE_V1_AUDIT")',
'    print("status =", payload["status"])',
'    print("layer =", payload["layer"])',
'    print("mode =", payload["mode"])',
'    print("stage =", payload["stage"])',
'    print("source_exists =", payload["source_exists"])',
'    print("runner_payload_ready =", payload["runner_payload_ready"])',
'    print("handoff_ready =", payload["handoff_ready"])',
'    if "summary" in payload:',
'        print("images_count =", payload["summary"]["images_count"])',
'    print("output_file =", str(out_file))',
'',
'if __name__ == "__main__":',
'    main()',
]
Path(r'D:\ECOM_LISTING_AGENT_MVP\compact_core_runner_handoff_gate_v1.py').write_text('\n'.join(lines) + '\n', encoding='utf-8')
