from pathlib import Path
lines = [
'import json',
'from pathlib import Path',
'',
'BASE = Path(r"D:\ECOM_LISTING_AGENT_MVP")',
'',
'def read_json(rel_path):',
'    p = BASE / Path(rel_path)',
'    if not p.exists():',
'        return {}, str(p), False',
'    return json.loads(p.read_text(encoding="utf-8")), str(p), True',
'',
'def main():',
'    decision_gate, decision_gate_path, decision_gate_exists = read_json(r"storage\state_compact_core\compact_core_stage9_decision_gate_v1.json")',
'    summary_data, summary_path, summary_exists = read_json(r"storage\state_compact_core\compact_core_stage9_summary_v1.json")',
'    checkpoint_data, checkpoint_path, checkpoint_exists = read_json(r"storage\state_compact_core\compact_core_checkpoint_v1.json")',
'    archive_dir = BASE / Path(r"storage\memory\archive")',
'    archive_dir.mkdir(parents=True, exist_ok=True)',
'    archive_payload = {}',
'    archive_payload["date"] = "2026-04-19"',
'    archive_payload["project"] = "ECOM_LISTING_AGENT_MVP_CONTROL_ROOM"',
'    archive_payload["stage"] = 9',
'    archive_payload["status"] = "STAGE_9_CONFIRMED_ARCHIVE_READY"',
'    archive_payload["stage9_confirmed"] = bool(decision_gate.get("stage9_ready")) and bool(decision_gate.get("decision_ready")) and decision_gate.get("decision") == "STAGE_9_CONFIRMED"',
'    archive_payload["decision"] = decision_gate.get("decision", "")',
'    archive_payload["decision_gate_exists"] = decision_gate_exists',
'    archive_payload["summary_exists"] = summary_exists',
'    archive_payload["checkpoint_exists"] = checkpoint_exists',
'    archive_payload["confirmed_layers_count"] = decision_gate.get("confirmed_layers_count", 0)',
'    archive_payload["confirmed_layers"] = summary_data.get("confirmed_layers", [])',
'    archive_payload["current_next_step"] = "archive_chat_and_open_new_chat_for_post_stage9_plan"',
'    archive_payload["achievements"] = [',
'        "stage9_reset_clean_completed",',
'        "compact_core_transition_front_v1_ok",',
'        "compact_core_state_hub_v1_ok",',
'        "compact_core_execution_bridge_v1_ok",',
'        "compact_core_preview_contract_v1_ok",',
'        "compact_core_preview_verification_v1_ok",',
'        "compact_core_preview_ready_gate_v1_ok",',
'        "compact_core_runner_payload_v1_ok",',
'        "compact_core_runner_handoff_gate_v1_ok",',
'        "compact_core_delivery_state_v1_ok",',
'        "compact_core_checkpoint_v1_ok",',
'        "compact_core_stage9_summary_v1_ok",',
'        "compact_core_stage9_decision_gate_v1_ok",',
'        "stage9_confirmed_without_live_jump"',
'    ]',
'    archive_payload["errors_this_chat"] = [',
'        "utf8_bom_or_feff_in_compact_core_state_hub_v1_and_preview_contract_v1",',
'        "broken___main___guard_in_preview_contract",',
'        "fragile_direct_echo_build_caused_missing_lines_and_missing_keys",',
'        "cmd_trap_with_special_characters_and_partial_line_writes",',
'        "archive_snapshot_failed_due_to_non_raw_windows_paths_and_invalid_escape_sequences",',
'        "late_chat_degradation_after_multiple_successful_steps"',
'    ]',
'    archive_payload["solutions_this_chat"] = [',
'        "first_do_real_audit_then_fix",',
'        "sanitize_bom_before_logic_repair",',
'        "if_file_breaks_twice_rebuild_full_file",',
'        "use_writer_script_for_fragile_python_files_instead_of_long_direct_echo_build",',
'        "always_use_raw_paths_for_windows_archive_and_state_paths",',
'        "before_sending_cmd_recheck_the_generated_logic_once_more"',
'    ]',
'    archive_payload["mandatory_rules_for_next_chat"] = [',
'        "project_specific_only",',
'        "one_step_only",',
'        "after_each_ok_audit_only_one_next_step",',
'        "no_live_operations_until_explicit_project_decision",',
'        "use_user_format_only",',
'        "include_previous_errors_and_fixes_in_every_transition_prompt"',
'    ]',
'    archive_file = archive_dir / "transition_stage9_chat_archive_v1.json"',
'    archive_file.write_text(json.dumps(archive_payload, ensure_ascii=False, indent=2), encoding="utf-8")',
'    prompt_lines = []',
'    prompt_lines.append("?? CONTINUATION - ECOM OS CONTROL ROOM (POST STAGE 9)")',
'    prompt_lines.append("")',
'    prompt_lines.append("ПРОЕКТ:")',
'    prompt_lines.append("ECOM_LISTING_AGENT_MVP")',
'    prompt_lines.append("")',
'    prompt_lines.append("Я продолжаю новый чат после архивации.")',
'    prompt_lines.append("")',
'    prompt_lines.append("ПОДТВЕРЖДЁННЫЙ СТАТУС:")',
'    prompt_lines.append("- Stage 9 confirmed")',
'    prompt_lines.append("- compact_core_stage9_decision_gate_v1 = OK")',
'    prompt_lines.append("- decision = STAGE_9_CONFIRMED")',
'    prompt_lines.append("- confirmed_layers_count = 10")',
'    prompt_lines.append("- Stage 9 archived in transition archive json")',
'    prompt_lines.append("")',
'    prompt_lines.append("ПОДТВЕРЖДЁННЫЕ СЛОИ STAGE 9:")',
'    for item in archive_payload["confirmed_layers"]:',
'        prompt_lines.append("- " + item)',
'    prompt_lines.append("")',
'    prompt_lines.append("ОШИБКИ ПРОШЛОГО ЧАТА, КОТОРЫЕ НУЖНО УЧИТЫВАТЬ:")',
'    for item in archive_payload["errors_this_chat"]:',
'        prompt_lines.append("- " + item)',
'    prompt_lines.append("")',
'    prompt_lines.append("КАК ИХ ИСПРАВЛЯЛИ / LESSONS LEARNED:")',
'    for item in archive_payload["solutions_this_chat"]:',
'        prompt_lines.append("- " + item)',
'    prompt_lines.append("")',
'    prompt_lines.append("ОБЯЗАТЕЛЬНЫЕ ПРАВИЛА РАБОТЫ В НОВОМ ЧАТЕ:")',
'    prompt_lines.append("- только project-specific линия")',
'    prompt_lines.append("- один шаг за раз")',
'    prompt_lines.append("- сначала проверка реального состояния, потом действие")',
'    prompt_lines.append("- после каждого OK audit только один следующий шаг")',
'    prompt_lines.append("- не использовать fragile direct echo-build там, где лучше writer-script")',
'    prompt_lines.append("- Windows paths писать через raw strings там, где создаются python-файлы")',
'    prompt_lines.append("- в каждом transition prompt явно указывать прошлые ошибки и как их исправляли")',
'    prompt_lines.append("")',
'    prompt_lines.append("МОЙ КАНОНИЧНЫЙ ФОРМАТ ОТВЕТА:")',
'    prompt_lines.append("1) Краткий анализ")',
'    prompt_lines.append("2) Один CMD блок")',
'    prompt_lines.append("3) Проверка")',
'    prompt_lines.append("4) Audit")',
'    prompt_lines.append("5) Что ожидаем")',
'    prompt_lines.append("")',
'    prompt_lines.append("ТЕКУЩАЯ ЦЕЛЬ НОВОГО ЧАТА:")',
'    prompt_lines.append("?? после подтверждённого Stage 9 построить новый структурированный план следующего этапа")',
'    prompt_lines.append("?? сначала сделать post-stage9 audit/plan, а не прыгать сразу в новые технические слои")',
'    prompt_lines.append("?? план должен быть пошаговый, структурированный, логичный, проверенный и учитывать ошибки прошлого чата")',
'    prompt_lines.append("")',
'    prompt_lines.append("ТЕКУЩИЙ NEXT STEP:")',
'    prompt_lines.append("?? build_post_stage9_direction_plan_v1")',
'    prompt_lines.append("")',
'    prompt_lines.append("АРХИВ ФАЙЛ:")',
'    prompt_lines.append(str(archive_file))',
'    prompt_text = "\n".join(prompt_lines) + "\n"',
'    prompt_file = archive_dir / "transition_stage9_chat_prompt_v1.txt"',
'    prompt_file.write_text(prompt_text, encoding="utf-8")',
'    print("TRANSITION_STAGE9_ARCHIVE_AND_PROMPT_AUDIT")',
'    print("status = OK")',
'    print("stage9_confirmed =", archive_payload["stage9_confirmed"])',
'    print("decision =", archive_payload["decision"])',
'    print("confirmed_layers_count =", archive_payload["confirmed_layers_count"])',
'    print("archive_file =", str(archive_file))',
'    print("prompt_file =", str(prompt_file))',
'',
'if __name__ == "__main__":',
'    main()',
]
Path(r'D:\ECOM_LISTING_AGENT_MVP\write_transition_archive_and_prompt_v1.py').write_text('\n'.join(lines) + '\n', encoding='utf-8')
